### PR TITLE
code refactored, general documentation added, lxml added to requireme…

### PR DESCRIPTION
**Pull request by NikolaJankovic**
…nts file

The code can be further refactored to have the private functions called outside of their "parents", meaning they would only have to be called once.

### CODE REVIEW

**Comment by anshumanv** [comment]
I'm not able to run it for some reason, are you sure `raw_input` works in python 3.6 and windows ?

**Comment by abhish311** [comment]
raw_input() only works on python2.7. 
For python 3 onwards it is just input ().

**Comment by anshumanv** [comment]
@abhish311 I'll merge this one since it has nice function organisation and comments, this will generate merge conflicts in your PR, so fix them alright ?
Then we can easily merge your PR

**Review by anshumanv — APPROVED** [review]
👍

**Comment by Yureien** [comment]
Hey, I have made a PR for Python 3-ification. @anshumanv

**Comment by anshumanv** [comment]
@FadedCoder merged

**Pull request merged**
