### PR TITLE
Resolved 1.Download files via links in terminal 2.Prevent those quali…

### PR DESCRIPTION
**Pull request by abhish311**
…ty of videos from downloading that are not present  3.Clean the script to make it more readable

### CODE REVIEW

**Comment by anshumanv** [comment]
Good Work !
Everything seems to be in place and working perfectly well except running into this error.
chia

**Comment by anshumanv** [comment]
I think it's probably due to non availability of some qualities of episodes, what do you think of this ?

**Comment by anshumanv** [comment]
I think #3 will fix this one, also I'll add you as collab after this PR is merged.

**Comment by abhish311** [comment]
Okay, I will fix that issue.

**Comment by anshumanv** [comment]
Thanks !

**Comment by anshumanv** [comment]
@abhish311 I have merged #5 , please continue in that organised code and make changes accordingly. Thanks 😄

**Comment by abhish311** [comment]
The new code does not cover for the exception cases and I have fixed the issue for the not in the list problem.

**Comment by anshumanv** [comment]
@abhish311 sending a new PR ?

**Comment by anshumanv** [comment]
@abhish311 why did you drop this ? It was working well.

**Pull request closed without merging**
