### PR TITLE
Feature/setup

### PR DESCRIPTION
**Pull request by wyj1026**
This is a setup script for this repo and I tested it successfully in linux.
Leave me a message if you hava any questions. :smile:

### CODE REVIEW

**Comment by anshumanv** [comment]
I'm commuting presently, will check in a while. :+1:

**Comment by anshumanv** [comment]
It shows merge conflicts presently, can you please solve them ?

**Comment by wyj1026** [comment]
I've fixed the conflicts.  : )

**Comment by Yureien** [comment]
Hey, the code seems alright, but I think the other libs in requirements.txt should be added too.

Also, is there a way to run `sudo pip3 install -r requirements.txt`, or is that unnecessary?

**Comment by anshumanv** [comment]
Thanks ! 👍 
Getting this error on windows, can you please look into this ?

```sh
  File ".\setup.py", line 13
    entry_points={
               ^
SyntaxError: invalid syntax
```

**Comment by anshumanv** [comment]
Is there any dependency i need to install ?

**Comment by Yureien** [comment]
I'm getting the error too on Linux.

**Comment by wyj1026** [comment]
Sorry about that, it should work now.

**Comment by anshumanv** [comment]
Thanks for the follow up @wyj1026 
The install ran successfully but not able to use it after install from terminal 
```sh
PS E:\Anshu\GIT\chia-anime-downloader> chia_anime_downloader search haikyuu
Traceback (most recent call last):
  File "C:\Users\Rohit\AppData\Local\Programs\Python\Python36\Scripts\chia_anime_downloader-script.py", line
ule>
    load_entry_point('chia-anime-downloader==1.0', 'console_scripts', 'chia_anime_downloader')()
  File "C:\Users\Rohit\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", l
 load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Rohit\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", l
n load_entry_point
    return ep.load()
  File "C:\Users\Rohit\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", l
n load
    return self.resolve()
  File "C:\Users\Rohit\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", l
n resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'chia_anime_downloader'
```

For some reason it's not getting installed globally, can you look into this please ? 😄

**Comment by Yureien** [comment]
This is working fine for me on Linux. @anshumanv have you tried running it as an admin?

**Comment by FadedCoder** [comment]
Btw, @wyj1026 I run into this error while uninstalling -
```
┬─[soham@Soham-Arch:~/chia-anime-downloader]─[02:20:27 PM]
╰─>$ sudo pip uninstall chia_anime_downloader                                                                                                                       14:20:27
Uninstalling chia-anime-downloader-1.0:
  /usr/bin/chia_anime_downloader
  /usr/bin/chia_anime_downloader.py
  /usr/lib/python3.6/site-packages/chia_anime_downloader-1.0-py3.6.egg
Proceed (y/n)? y
  Successfully uninstalled chia-anime-downloader-1.0
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    load_entry_point('pip==9.0.1', 'console_scripts', 'pip')()
  File "/usr/lib/python3.6/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/usr/lib/python3.6/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.6/site-packages/chia_anime_downloader-1.0-py3.6.egg'
```

**Comment by anshumanv** [comment]
Tried running as admin, same issues @FadedCoder.

**Comment by Yureien** [comment]
@anshumanv Try `python -m chia_anime_downloader`

**Comment by anshumanv** [comment]
Doesn't work, says module not found.

**Comment by wyj1026** [comment]
I don't have a windows computer, so I have no idea why it doesn't work on windows. 😞

**Comment by anshumanv** [comment]
Alright, thanks @wyj1026

**Review by anshumanv — APPROVED** [review]
👍

**Comment by Yureien** [comment]
No worries. I'll find a fix later on. First, let's complete the scraper.

**Pull request merged**
