### PR TITLE
Allow download through wget

### PR DESCRIPTION
**Pull request by zuik**
Follow up to #8

### CODE REVIEW

**Comment by anshumanv** [comment]
Thanks for this @zuik , however I'm facing this error.
Can you please look into this, I'm running python 3.6.2
chia2
Download in #4 was working well but the PR was unfortunately closed, look into it if you need any references.

**Comment by anshumanv** [comment]
Btw congrats on crossing 1k gh contributions. 🎉

**Comment by Yureien** [comment]
Hey, in my opinion, we should use requests to download. This will lessen the amount of libs required to use this.

**Comment by zuik** [comment]
@FadedCoder I agree. We could leave this as an option but should default to requests.
@anshumanv  I think the problem is that Window doesn't have `wget` binary so that you get a file not exist error. And also thank you :)

**Comment by anshumanv** [comment]
@zuik any ideas on how to make it work on windows ?

**Comment by zuik** [comment]
We could bundle wget binary with it. But that has its own challenges. I gonna look into doing it through requests

**Comment by anshumanv** [comment]
Alright thanks, refer #4 if needed, it was working like a charm

**Comment by Yureien** [comment]
@zuik Please change it into requests. It will cause errors otherwise on systems where wget is not installed. Refer this if you need help - https://stackoverflow.com/a/16696317/5210825.

**Comment by Yureien** [comment]
Closing this as PR #16 resolves this.

**Pull request closed without merging**
