### PR TITLE
Add arguments to the script.

### PR DESCRIPTION
**Pull request by zuik**
- For now, it is very simple and relies on the method. I will later add support for downloader as mentioned in #5.
- Also, I added logging to the script.

Ref. issue #7

### CODE REVIEW

**Review by anshumanv — APPROVED** [review]
Works Well ! 👍

**Comment by anshumanv** [comment]
Please send a PR as #4 as well

**Comment by anshumanv** [comment]
Hey @zuik could you try saving links for naruto from episode 1-10 in quality other than 360p ? It aint saving any links in text file for qualities other than 360p for me.

**Comment by Yureien** [comment]
@anshumanv that's cause only 360p is available for Naruto eps 1-10. Fix coming up in an hour.

**Comment by anshumanv** [comment]
Alright, thanks.

**Pull request merged**
